### ISSUE TITLE
Parser fails when event with no link element imported

### ISSUE THREAD

**Issue by aviaryan** [niranjan94/python-pentabarf-xml#1]
In PentabarfParser.py, around line 74, we have - 

```python
                    links_element = event_element.find('links')
                    for link_element in links_element.findall('link'):
                        link_url = link_element.get('href')
                        if not event.video_url and ('mp4' in link_url
                                                    or 'webm' in link_url
                                                    or 'youtube' in link_url
                                                    or 'avi' in link_url):
```

If there is no `links` element in xml, then `links_element` is None and so the for loop in the next line will throw an exception. 

```
  File "/Users/aviaryan/miniconda2/lib/python2.7/site-packages/pentabarf/PentabarfParser.py", line 74, in parse
    for link_element in links_element.findall('link'):
AttributeError: 'NoneType' object has no attribute 'findall'
```

**Comment by niranjan94** [comment]
@aviaryan thanks :) ... This was built in a short time so didn't have time to test it at all ...

**Comment by aviaryan** [comment]
@niranjan94 Happy to help. 😄 I am currently testing import/export of [open-event](https://github.com/fossasia/open-event-orga-server/issues/2881) so I will report more issues if I find them. Should I send a PR for this?

**Comment by niranjan94** [comment]
If you can send a PR, that's awesome :) ... No problem otherwise too ... I'll fix it in a day or two ... Working on something else .. So a bit busy now
